##### Stage 1
FROM node:lts AS node
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod

##### Stage 2
FROM nginx:alpine
VOLUME /var/cache/nginx
COPY --from=node /app/dist/aragosta-app /usr/share/nginx/html
COPY ./config/dev/nginx.conf /etc/nginx/nginx.conf
COPY ./config/dev/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# docker build -t nginx-angular -f nginx.prod.dockerfile .
# docker run -p 8080:80 nginx-angular

