##### Stage 1: Build Angular Application
FROM node:lts-alpine AS build
WORKDIR /app

# Make sure we got brotli
RUN apk update
RUN apk add --upgrade brotli

# NPM install and build
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build:dev

# Compress the files using Brotli
#RUN apk add brotli
RUN cd /app/dist && find . -type f -exec brotli {} \;

##### Stage 2: Nginx with HTTP/3 support
FROM ghcr.io/macbre/nginx-http3:latest

# Copy the Angular app from the build stage
COPY --from=build /app/dist/aragosta-app /usr/share/nginx/html
# Copy Nginx configuration files
COPY ./config/dev/default.conf /etc/nginx/conf.d/default.conf
COPY ./config/prod/compression.conf /etc/nginx/conf.d/compression.conf

# Expose ports for HTTP
EXPOSE 80
