services:
  app:
    image: blou5/arg-app:latest
    ports:
      - "4200:80"
      - "4201:443"
    networks:
      - arg
    volumes:
      - ${PUBLIC_KEY}:/etc/ssl/aragosta.crt:r
      - ${PRIVATE_KEY}:/etc/ssl/aragosta.key:r
networks:
  arg:
    driver: bridge
