services:
  app:
    image: blou5/arg-app:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - arg
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email quantum.pixel2025@gmail.com -d aragosta.al --agree-tos
    networks:
      - arg
    restart: unless-stopped

networks:
  arg:
    driver: bridge
