services:
  app:
    image: blou5/arg-app:latest
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - arg

networks:
  arg:
    driver: bridge
