services:
  app:
    build:
      context: ../..
      dockerfile: arg-docker/arg-local-app/Dockerfile
    volumes:
      - ../../dist/aragosta-app:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - arg
  postgres:
    image: 'postgres:16.1-alpine'
    container_name: arg-db
    environment:
      POSTGRES_DB: arg
      POSTGRES_PASSWORD: arg
      POSTGRES_USER: arg
    ports:
      - '5432:5432'
    networks:
      - arg
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: blou5/arg-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: local
      SWAGGER_ENABLED: true
      DATABASE_URL: jdbc:postgresql://postgres/arg
    ports:
      - "8080:8080"
      - "8000:8000"
      - "3128:3128"
    networks:
      - arg
    depends_on:
      postgres:
        condition: service_started

  py:
    container_name: arg_db_initialize
    build:
      context: ../..
      dockerfile: arg-docker/arg-local-app/DbInitialize
    env_file:
      - .env
    networks:
      - arg
    depends_on:
      api:
        condition: service_healthy

volumes:
  pgdata:

networks:
  arg:
    driver: bridge
