name: E-Commerce-app-cd

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  ci:
    uses: quantum-pixel-team/ci-cd-templates/.github/workflows/app-ci-angular.yml@master
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_REQ_TOKE: ${{secrets.GITHUB_TOKEN}}


